import type { Metadata } from "next";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";
import { DeviceContextProvider } from "@/context/deviceContext";

const inter = Pixelify_Sans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} flex justify-center items-center w-full h-screen`}>
				<DeviceContextProvider>
					<section className="flex flex-col gap-[30px] border-solid border-8 box-border border-black justify-start items-center bg-gradient-to-br p-[32px] pt-[64px] from-[#B63838] to-[#B22424] h-screen w-full sm:max-h-[930px] max-w-[430px] rounded-md">
						{children}
					</section>
				</DeviceContextProvider>
			</body>
		</html>
	);
}
