import type { Metadata } from "next";
import { Martel_Sans } from "next/font/google";
import "./globals.css";

const inter = Martel_Sans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center items-center w-full h-screen`}>{children}</body>
    </html>
  );
}
